afrix-job-hunter/scrapers/job-hunter/config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resource :sessions, only: [:new, :create, :destroy]

  resource :users do
    resources :jobs, only: [:new, :index, :show, :destroy]
  end
  get 'login'       => 'sessions#new'
  get 'signup'      => 'users#new'
  get 'users/match' => 'jobs#match'
  get 'users/apply' => 'jobs#apply'
  get '/search'     => 'jobs#search'

 resources :jobs do
   collection do
     delete 'destroy_multiple'
   end
 end
end

afrix-job-hunter/scrapers/job-hunter/app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  validates :title, :company, :description, presence: true
  validates_uniqueness_of :title, scope: [:company, :url, :description]
  paginates_per 25

  scope :match, -> { where('score > 40') }
  scope :applied, -> { where('applied = ?', true) }

  def self.hex(id)
    Digest::MD5.hexdigest id
  end

  def to_param
    hex_id
  end

  def self.logo_validator(url)
    res = Faraday.get("https://logo.clearbit.com/#{url}")
    unless res.status == 200
      "https://placeholdit.imgix.net/~text?txtsize=22&txt=I+was+unable+to+find+your+logo+sorry&w=140&h=140&txttrack=0"
    else
      "https://logo.clearbit.com/#{url}"
    end
  end

  def self.autocomplete(name)
    res = Faraday.get("https://autocomplete.clearbit.com/v1/companies/suggest?query=:#{name}")
    url = JSON.parse(res.body)[0]["domain"]
    Job.logo_validator(url)
    rescue
      "https://placeholdit.imgix.net/~text?txtsize=22&txt=I+was+unable+to+find+your+logo+sorry&w=140&h=140&txttrack=0"
  end

  # Searches for jobs.
  def self.get_jobs(scraper, user, title = "", location = "", pages = "")
    %x(bin/rails r #{scraper}.rb "#{user.id}" "#{title}" "#{location}" "#{pages}")
  end

  # Apply for the matching jobs.
  def self.apply(user, jobs, applier)
    jobs.each do |job|
      unless job.applied
        %x(bin/rails r #{applier}.rb "#{user.id}" "#{job.id}")
      end
    end
  end
end

afrix-job-hunter/scrapers/job-hunter/app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, :last_name, :email, :phone_number, :document, presence: true
  validates :first_name, :last_name, length: { in: 2..20 }
  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :phone_number, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }
  validates :username, uniqueness: true
  has_many :jobs
  has_secure_password
  has_attached_file :document
  validates_attachment :document, content_type: { content_type: %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }

  def get_number_of_repos(user_name)
    response = HTTParty.get("https://api.github.com/users/#{user_name}/repos")
    number = response.length
    names_of_projects =[]
    (0..number-1).each do |i|
      names_of_projects << response[i]["name"]
    end
    names_of_projects
  end

  def get_the_bytes(user_name)
    names = get_number_of_repos(user_name)
    ruby_bytes = []
    lines = []
    names.each do |name|
      response = HTTParty.get("https://api.github.com/repos/#{user_name}/#{name}/languages")
      ruby_bytes << response["Ruby"]
    end
    ruby_bytes.each do |project|
      unless project == nil
        lines << project/40
      end
    end
    [lines.reduce(:+), names.length]
  end
end

afrix-job-hunter/scrapers/job-hunter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper
  protect_from_forgery with: :null_session
end

afrix-job-hunter/scrapers/job-hunter/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :require_logged_in, only: [:new, :index, :match, :destroy]

  def new
    @job = Job.new
  end

  def search
    params['angel_scraper'] == 'yes' ? applier = 'angelscraper' : applier = 'scraper'
    @jobs = Job.get_jobs(applier, current_user, params[:title], params[:location], params[:pages])
    redirect_to users_jobs_path
  end

  def match
    @user = current_user
    @jobs = Job.match.order(:id).page params[:page]
  end

  def apply
    @user = current_user
    params['angel_applier'] == 'on' ? applier = 'angelapplier' : applier = 'applier'
    Job.apply(@user, Job.match, applier)
    redirect_to users_match_path
  end

  def show
    @job = Job.find_by(hex_id: params[:id])
    @user = current_user || User.find(@job.user_id)
  end

  def index
    @user = current_user
    @jobs = Job.order(:id).page params[:page]
  end

  def create
    @job = Job.new(job_params)
    @job.save
  end

  def destroy
    Job.delete_all
    Job.reset_pk_sequence
    redirect_to users_jobs_path
  end

  def destroy_multiple
    Job.destroy(params[:jobs]) unless params[:jobs].nil?
    redirect_to users_match_path
  end

  private
    def job_params
      params.require(:job).permit(:title, :company, :description)
    end
end

afrix-job-hunter/scrapers/job-hunter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username]).try(:authenticate, params[:password])
    if @user
      # logged in
      flash[:success] = "Welcome to the Job Hunter, #{@user.first_name}!"
      log_in @user
      redirect_to users_jobs_path
    else
      flash.now[:danger] = "Invalid email/password combination."
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

afrix-job-hunter/scrapers/job-hunter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    @user.document = user_params[:document]
    unless user_params[:github] == ""
      @user.number_of_lines, @user.number_of_projects = @user.get_the_bytes(user_params[:github])
    end
    if @user.save
      log_in @user
      flash[:success] = "Signed up was successful! Welcome, #{@user.first_name}!"
      redirect_to users_jobs_path
    else
      render 'new'
    end
  end

  def update
    current_user.update(user_params)
    redirect_to users_jobs_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :first_name,
                    :last_name, :email, :phone_number, :github, :linkedin, :document)
    end
end

afrix-job-hunter/scrapers/job-hunter/app/helpers/application_helper.rb
module ApplicationHelper
end

afrix-job-hunter/scrapers/job-hunter/app/helpers/jobs_controller_helper.rb
module JobsControllerHelper
end

afrix-job-hunter/scrapers/job-hunter/app/helpers/jobs_helper.rb
module JobsHelper
end

afrix-job-hunter/scrapers/job-hunter/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def require_logged_in
    return true if current_user
    redirect_to root_path
    return false
  end
end

afrix-job-hunter/scrapers/job-hunter/app/helpers/users_helper.rb
module UsersHelper
end

afrix-job-hunter/scrapers/job-hunter/app/views/jobs/index.html.erb
<h4>Jobs Found</h4>
<div class= "container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <%= paginate @jobs %>
      <%= react_component('JobsBox', jobs: @jobs) %>
      <%= paginate @jobs %>

      <%= form_tag("/search", method: "get") do %>
      <%= label_tag(:title, "Enter job title or keywords") %>
      <%= text_field_tag(:title, nil, placeholder: 'Job Title') %>
      <%= label_tag(:location, "Enter city, state or zip code") %>
      <%= text_field_tag(:location, nil, placeholder: 'City') %>
      <%= label_tag(:pages, "Pages to inspect (not needed for angel site)") %>
      <%= number_field_tag(:pages, nil, placeholder: 'Number of Pages') %>
      <p> Select website to get jobs from (angel.co is default) </p>
      <%= check_box_tag 'angel_scraper', 'yes', true %> <p>Angel</p>
      <%= check_box_tag 'indeed_scraper' %> <p>Indeed</p>
      <%= submit_tag("Find Jobs") %>
      <% end %>

      <%= form_for @user, url: users_path, html: { multipart: true } do |f| %>
      <%= f.file_field :document %>
      <%= f.submit "Update Resume", class: "btn btn-primary" %>
      <% end %>
      <p>
        <form method="get" action="match" class="button_to">
          <input value="Match Jobs" type="submit" />
        </form>
      </p>
      <p>
        <form method="get" action="apply" class="button_to">
          <input value="Apply to Jobs" type="submit" />
        </form>
      </p>
      <p>
        <%= button_to "Delete Jobs", {:controller => :jobs, :action => 'destroy', :id => @user.id },
        :method => :delete %>
      </p>
    </div>
  </div>
</div>

afrix-job-hunter/scrapers/job-hunter/app/views/jobs/match.html.erb
<h4>Job Matches</h4>
<div class= "container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-12">
      <p><%= paginate @jobs %></p>
      <p><%= link_to "Back To General Jobs", users_jobs_path %></p>
      <%= form_tag destroy_multiple_jobs_path, method: :delete do %>
      <table class="table table-striped table-bordered table-condensed">
        <tr>
          <th class="text-center"> Job </th>
          <th class="text-center"> Job ID </th>
          <th class="text-center"> Job Hex_ID </th>
          <th class="text-center"> Title </th>
          <th class="text-center"> Company </th>
          <th class="text-center"> Location </th>
          <th class="text-center"> Description </th>
          <th class="text-center"> Score </th>
          <th class="text-center"> Post Date </th>
          <th class="text-center"> URL </th>
          <th class="text-center"> Applied </th>
        </tr>
        <% @jobs.each do |job| %>
        <td class="text-center"><%= check_box_tag "jobs[]", job.id %></td>
        <td class="text-center"><%= "#{job.id}" %></td>
        <td class="text-center"><%= "#{job.hex_id}" %></td>
        <td class="text-center"><%= "#{job.title}" %></td>
        <td class="text-center"><%= "#{job.company}" %></td>
        <td class="text-center"><%= "#{job.location}" %></td>
        <td class="text-center"><%= truncate("#{job.description}", length: 100) %></td>
        <td class="text-center"><%= "#{job.score.round(2)}" %></td>
        <td class="text-center"><%= "#{job.post_date}" %></td>
        <td class="text-center"><%= "#{job.url}" %></td>
        <td class="text-center"><%= "#{job.applied}" %></td>
      </tr>
      <% end %>
    </table>
    <%= submit_tag "Delete Selected Jobs" %>
    <% end %>
    <br>

    <p><%= paginate @jobs %></p>
    <p><%= link_to_if !@user.document.url.nil?, 'Resume', @user.document.url %></p>

    <form method="get" action="apply" class="button_to">
      <p> Select website jobs to apply </p>
      <input type="checkbox" name="angel_applier" checked>Angel<br>
      <input type="checkbox" name="indeed_applier">Indeed<br>
      <input value="Apply to Jobs" type="submit" />
    </form>

    <p><%= link_to "Back To General Jobs", users_jobs_path %></p>
    </div>
  </div>
</div>

afrix-job-hunter/scrapers/job-hunter/app/views/jobs/new.html.erb
<%= form_for(search_path, action: "search", method: :get) do |f| %>
  <h6>what</h6>
  <%= f.text_field :title %>
  <h6>Enter job title or keywords</h6>
  <h6>where</h6>
  <%= f.text_field :location %>
  <h6>Enter city, state or zip code</h6>
  <%= f.submit "Search" %>
<% end %>

afrix-job-hunter/scrapers/job-hunter/app/views/jobs/show.html.erb
<div class= "container">
  <%= react_component( 'CoverPage', job: @job, user: @user) %>
</div>

<script>
window.onload = function start_count() {

  var bar = new ProgressBar.SemiCircle(progressbar, {
    strokeWidth: 6,
    color: '#FFEA82',
    trailColor: '#eee',
    trailWidth: 5,
    easing: 'easeIn',
    duration: 4000,
    svgStyle: null,
    text: {
      value: '',
      alignToBottom: true
    },
    from: { color: '#ffff00 ' },
    to: { color: '#00ff00' },
    step: function step(state, bar) {
      bar.path.setAttribute('stroke', state.color);
      var value = Math.round(bar.value() * 100);
      if (value === 0) {
        bar.setText('');
      } else {
        bar.setText(value);
      }

      bar.text.style.color = state.color;
    }
  });

  bar.text.style.fontFamily = '"Ubuntu", Helvetica, sans-serif';
  bar.text.style.fontSize = '2.5em';

  bar.animate("<%= @job.score/100 %>");
  var numAnim = new CountUp("number-lines", 0, "<%= @user.number_of_lines %>", 0, 4);
  window.setTimeout(numAnim.start, 2000)
  var numAnimtoo = new CountUp("number-projects", 0, "<%= @user.number_of_projects %>", 0, 4);
  window.setTimeout(numAnimtoo.start, 2000)
}
</script>

afrix-job-hunter/scrapers/job-hunter/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

afrix-job-hunter/scrapers/job-hunter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobHunter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Google Analytics -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-76667906-1', 'auto');
  ga('send', 'pageview');
  </script>
  <!-- End Google Analytics -->
</head>
<body>
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</body>
</html>

afrix-job-hunter/scrapers/job-hunter/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

afrix-job-hunter/scrapers/job-hunter/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: users_path, html: { multipart: true } do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "First Name", class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: "Last Name", class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, placeholder: "Email", class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.phone_field :phone_number, placeholder: "xxx-xxx-xxxx", class: 'form-control' %>

      <%= f.label :github %>
      <%= f.text_field :github, placeholder: "Github Username", class: 'form-control' %>

      <%= f.label :linkedin %>
      <%= f.text_field :linkedin, placeholder: "LinkedIN", class: 'form-control' %>

      <%= f.label :username %>
      <%= f.text_field :username, placeholder: "Username", class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "Password", class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, placeholder: "Retype Password", class: 'form-control' %>

      <%= f.file_field :document %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    <p><%= link_to "Back to Login", login_path %></p>
  </div>
</div>